version: "3.9"
services:
  postgres:
    image: postgres:16-alpine3.20
    environment:
      POSTGRES_DB: 'web_application'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0123
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/web_application
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 0123

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile-front
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production